apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alias-ai

resources:
  - alias-gateway.yaml
  - nim-nemotron.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: alias-ai
  app.kubernetes.io/managed-by: kustomize
  nvidia.gtc/contest: berlin-2026
